site_name: Qubic Capital - Whitepaper
site_description: Whitepaper

theme:
  name: material
  language: en
  logo: assets/logo2.png
  favicon: assets/logo2.png
  palette:
    - scheme: slate
      primary: black
      accent: teal
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.highlight
    - content.code.copy

extra_css:
  - styles/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra:
  generator: false
  
nav:
  - Home: index.md
  - 1. Introduction: 01-introduction.md
  - 2. Smart Contracts in Qubic: 02-smart-contracts-in-qubic.md
  - 3. Ownership Concentration: 03-ownership-concentration.md
  - 4. The Qubic Capital Solution: 04-the-qubic-capital-solution.md
  - 5. Strategic Vision: 05-strategic-vision.md
  - 6. Governance: 06-governance.md
  - 7. Tokenomics: 07-tokenomics.md
  - 8. How to Buy $QCAP: 08-how-to-buy-qcap.md
  - 9. Long-Term Alignment: 09-long-term-alignment.md
